version: "3.7"
services:
  app:
      build:
        args:
          user: sammy
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      container_name: api-download-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - api

  nginx:
    image: nginx:1.17-alpine
    container_name: api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
    networks:
      - api

  db:
    image: mysql
    restart: always
    ports:
      - 3010:3006
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    networks:
      - api

networks:
  api:
    driver: bridge